#!/bin/bash
if [ -z "$1" ]; then
	echo uso: $0 directorio
	exit
fi
SRCD=$1
TGTD="/home/mud"
OF=fficmud2ninetears-$(date +%Y%m%d).tar
LAST=fficmud2ninetears.last.tar.bz2
tar -cf $TGTD$OF $SRCD
bzip2 $TGTD$OF
ln -s $TGTD$OF.bz2 $TGTD/$LAST
#rm -rf /home/mud/$LAST
ls -la /home/mud/$OF.bz2 > /home/mud/log/backup_mud.log
ls -la /home/mud/$OF.bz2 >> /home/mud/log/backup_mud_full.log
cat /home/mud/log/backup_mud.log | mail mud@driade.fadlan.com -s $OF
		
