  // Comandos genéricos
  "enterrar"    : ({ "/comandos/genericos/enterrar", "inicio" }),
  "considerar"  : ({ "/comandos/genericos/considerar", "inicio" }),
  "reparar"     : ({ "/comandos/genericos/reparar","inicio" }),
  "juzgar"      : ({ "/comandos/genericos/juzgar","inicio" }),

  // Comandos de Shaman
  "invocar"     : ({ "/d/gremios/comandos/invocar", "inicio" }),
  "marcaoscura" : ({ "/d/gremios/comandos/marcaoscura", "inicio" }),

  // Comandos de Khurgars
  "decapitar"   : ({ "/comandos/khurgar/decapitar", "inicio" }),
  "cabezazo"    : ({ "/comandos/khurgar/cabezazo", "inicio" }),
  "furia"	: ({ "/comandos/khurgar/furia", "furia" }),
      
  // Comandos de Bárbaros del Caos
  "aplastar"    : ({ "/comandos/barbarocaos/aplastar", "inicio" }),
  "cazar"       : ({ "/comandos/barbarocaos/cazar", "inicio" }),
  "despellejar" : ({ "/comandos/barbarocaos/despellejar", "despellejar" }),
  "curtir"      : ({ "/comandos/barbarocaos/curtir", "inicio" }),
  
  // Comandos de Caballeros de JaDe
  "cargar"      : ({ "/comandos/caballerojade/carga", "inicio" }),
  "golpeescudo" : ({ "/comandos/caballerojade/golpe", "inicio" }),
  "drenar"	: ({ "/comandos/caballerojade/drenar", "inicio" }),
// En pruebas      
  "barrido"       : ({ "/comandos/turkhun/barrido", "inicio"}),
  "esconderse"    : ({ "/comandos/turkhun/hide_in_shad", "inicio"})
