/* this file automatically generated by the Makefile */
#define COMPILER "gcc"
#define OPTIMIZE "-O2 -fomit-frame-pointer -fstrength-reduce"
#define CFLAGS   "-D__USE_FIXED_PROTOTYPES__ -rdynamic -O2 -fomit-frame-pointer -fstrength-reduce"
#define OBJDIR   "obj"
